### ISSUE TITLE
[Tribute] Must pass in a DOM node or NodeList.

### ISSUE THREAD

**Issue by Alex61NN5** [ladderio/ngx-tribute#6] opened 2018-12-04 23:19 UTC
Hey There,
I keep getting this error...

`[Tribute] Must pass in a DOM node or NodeList.` 

now this doesnt actually affect functionality, it works fine but I get this error sporadically.

My set up is as follows

### Angular Version
```
Angular CLI: 1.7.4
Node: 9.2.1
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.4
@angular/service-worker: 5.2.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.0.40
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.2
typescript: 2.4.2
webpack: 3.11.0
```

###  Component Setup
```
object = [];

TRIBUTE = new tribute({
    values: this.object,
    menuItemTemplate: function(item) {
      return `
        <div class="user-mention-container">
          <img src="${item.original.avatar}" class="avatar">
          <div class="user-container">
            <p>${item.string}</p>
            <p class="user-email">${item.original.email}</p>
          </div>
        </div>
        `;
    },
    menuContainer: document.getElementById('mention-container'),
    positionMenu: true
  });

getAllUsers(tenantId: number): void {
    this._service.getAllUsers(tenantId)
      .subscribe((result) => {
        this.users$ = result;
        if (result.length > 1) {
            let object;
            this.TRIBUTE.attach(document.getElementById('commentBox'));
            this.users$.forEach((element) => {
            object = {
              key: `${element.firstName} ${element.surname}`,
              value: `${element.firstName} ${element.surname}`,
              id: element.id,
              email: element.emailAddress,
              avatar: (element.profilePicture) ? `data:image/jpeg;base64, ${element.profilePicture}` : `../../../assets/img/default-profile-picture.png`
            };
            this.object.push(object);
        });
      }
    });
  }
```

I'm not sure exactly what could be causing this issue.

**Comment by Alex61NN5** [comment] 2019-01-10 00:36
Any Ideas?

**Comment by agarbund** [comment] 2019-01-10 07:55
Can you create a full reproduction eg. on Stackblitz? It's not clear what's assigned to `this.TRIBUTE` and `this.object`.

Also your way of getting async data for selection seems to be done non-standard way. Can you try to do it as documented in [Tributejs docs](https://github.com/zurb/tribute#loading-remote-data)

**Comment by Alex61NN5** [comment] 2019-01-11 05:53
I have updated my question to make it clearer whats assigned to `this.TRIBUTE` and `this.object` as for a reproduction I've been unable to reproduce the error it seems to happen sporadically.  

As for getting data I'm just using an `observable` and on the return of the data generate the tribute module, it doesn't make sense in my project to do it the way the JS Tribute way since this is an angular application.

**Comment by agarbund** [comment] 2019-01-18 09:56
Btw are you using `[ngxTribute]` directive at all? It doesn't seem so as you're attaching Tribute instance manually with `this.TRIBUTE.attach(document.getElementById('commentBox'));`. If you're using Tribute.js directly, not via `[ngxTribute]` directive, this issue should rather be posted on Tribute.js Github page

**Closed** 2019-04-24 08:59 UTC
Labels: question
